### ISSUE TITLE
Firefox, text doesn't wrap

### ISSUE THREAD

**Issue by AlexBryson** [Monchoman45/Torus#14]
![image](https://cloud.githubusercontent.com/assets/8709821/7062621/f90f4006-de96-11e4-9915-08fd8fcde571.png)

Working in chrome

**Comment by Monchoman45** [comment]
Caused by [`#torus-window {white-space: pre;}`](https://github.com/Monchoman45/Torus/blob/master/ui/main.css#L245), which is necessary for getting multiple spaces in a row to show up as more than one space.

Will probably solve by wrapping the timestamp and the user in a span with `white-space: pre;` and taking it off `#torus-window`.

**Comment by Monchoman45** [comment]
Ended up just wrapping the space itself in a span. Probably a stupid solution, but if I may [quote myself](https://github.com/Monchoman45/Torus/blob/master/ui/render.js#L93):

> `//#yolo`
